### ISSUE TITLE
GPG Key file download

### ISSUE THREAD

**Issue by redhatrises** [CrowdStrike/ansible_collection_falcon#12]
Need to be able to download and install the gpg key from the api. Some Linux Oses default to having gpgcheck on.

**Comment by shawndwells** [comment]
Paging @jshcodes or @crowdstrikedcs. Is this possible?

**Comment by crowdstrikedcs** [comment]
Looks like we only keep the key in the UI. Sounds like we should reach out on that. But we could stage it on git and download it at install.

On Dec 18, 2020, at 21:47, Shawn Wells <notifications@github.com> wrote:

﻿

Paging @jshcodes [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jshcodes&d=DwMCaQ&c=08AGY6txKsvMOP6lYkHQpPMRA1U6kqhAwGa8-0QCg3M&r=9okQcjbCccFttQdexKXlVIU8TjH2iVMw7dU8iCd-__M&m=ZuVILVgYUuOdxFgQfLEi5qLy3EOjpyMjHFgi9BXq9_U&s=zb96F_baV96fNAM5VUOzTowFDRjRmSq_4vSdYjOO9l8&e=> or @crowdstrikedcs [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_crowdstrikedcs&d=DwMCaQ&c=08AGY6txKsvMOP6lYkHQpPMRA1U6kqhAwGa8-0QCg3M&r=9okQcjbCccFttQdexKXlVIU8TjH2iVMw7dU8iCd-__M&m=ZuVILVgYUuOdxFgQfLEi5qLy3EOjpyMjHFgi9BXq9_U&s=ZlbyQ7TSB6jaimwi1pg6nt6SHj-wDX39W-DnxaPDb4o&e=>. Is this possible?

**Comment by jshcodes** [comment]
If we can get it we can install it.  Are they logged into the API or do we have creds in this scenario?  (I have a variation in a bootstrap that pulls from the API...)

**Comment by crowdstrikedcs** [comment]
We're looking to get this right?  (Falcon Linux Sensor RPM Signing, GPG Key). It's not in the API as far as i know. I was thinking we could just stage it in the repo.

**Comment by jshcodes** [comment]
Works for me! ( and is easier :grin: )

**Comment by redhatrises** [comment]
Keeping it in GIT is a temporary solution and is not ideal in case the keys ever are updated or regenerated. It would be way better for everything to be accessible through the API. So, long term we need to enable the API to be able to access "other downloads" as this is good UX. In general, the Falcon UI should be accessing the API calls for each action itself, so if there is someone I need to push to get this started, please let me know are there are some additional information that the API needs to provide in the sensor download section.

**Comment by crowdstrikedcs** [comment]
Checking with API team on this. Will you send other use cases as well.

**Comment by redhatrises** [comment]
I will thanks!

**Comment by ppanon2022** [comment]
Another use case is using Uyuni with a custom software channel to deploy the package.

**Comment by bschonec** [comment]
This issue is almost two years old.  Why can't Crowdstrike just make the GPG key available in a yum repository somewhere?
