### ISSUE TITLE
v3.2.2 - Error on task "Gather tmp install directory objects (Windows)"

### ISSUE THREAD

**Issue by ktinthecloud** [CrowdStrike/ansible_collection_falcon#134]
Getting the following error on the "Gather tmp install directory objects (Windows)" task:

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Gather tmp install directory objects (Windows)] *********************************************************************************
fatal: [hostname]: FAILED! => {"changed": false, "msg": "argument for paths is of type System.Collections.Hashtable and we were unable to convert to list: System.Collections.Hashtable cannot be converted to a list"}

**Comment by jurschel** [comment]
I second this issue.  Seems like something broke recently.  I had to go back to 3.1.0 to get a version that wouldn't error on windows boxes...

**Comment by carlosmmatos** [comment]
@ktinthecloud @jurschel We believe the issue has been resolved with #135 

We'll leave this open until we hear back to confirm the above resolution.

**Comment by jurschel** [comment]
You can close it out.  I tested it earlier this morning and it now does indeed work as expected.  Thanks for the quick response!

**Comment by ktinthecloud** [comment]
Yep, it's working now.  Thanks @carlosmmatos & @redhatrises!

**Comment by ktinthecloud** [comment]
> @ktinthecloud @jurschel We believe the issue has been resolved with #135
> 
> We'll leave this open until we hear back to confirm the above resolution.

Yep, it's working now. Thanks @carlosmmatos & @redhatrises!
