### ISSUE TITLE
Get list of Supported Kernels failed with 403 Authorization failed

### ISSUE THREAD

**Issue by yudigoh** [CrowdStrike/ansible_collection_falcon#154]
Using the latest crowdstrike.falcon collection version 3.2.7 

upon executing [Get list of Supported Kernels](https://github.com/CrowdStrike/ansible_collection_falcon/blob/ce79850be7b6f6b11ca1823d38fab985a7e1f2e1/roles/falcon_install/tasks/api.yml#L95) which translates to this call:

```
https://api.crowdstrike.com/policy/combined/sensor-update-kernels/v1?filter=vendor%3A%22redhat%22%2Brelease%3A%224.18.0-240.10.1.el8_3.x86_64%22
```

throws 403

```
{
  "meta": {
    "query_time": 9.4e-8,
    "powered_by": "crowdstrike-api-gateway",
    "trace_id": "0c39bdc5-8e52-4d8a-9c6c-4b8854e8a8aa"
  },
  "errors": [
    {
      "code": 403,
      "message": "access denied, authorization failed"
    }
  ]
}
```

Tested with the swagger page to replicate the error and my OAuth2 token works with other API calls.

**Comment by redhatrises** [comment]
Hello,

Does your api client/key have `Sensor update policies: read` enabled?

**Comment by carlosmmatos** [comment]
@yudigoh We've updated the role docs to be more specific about the type of API scopes needed when using the api installation method. 

Let us know if @redhatrises comment above fixed your issue.

**Comment by yudigoh** [comment]
Thank you @carlosmmatos and @redhatrises. Closing the issue
