### ISSUE TITLE
"Example of deleting options" Doesn't work

### ISSUE THREAD

**Issue by TyraelTLK** [CrowdStrike/ansible_collection_falcon#158]
From doc:

Examples of deleting options:

- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_configure
    vars:
      falcon_option_state: no
      falcon_cid: ""
      falcon_tags: ""
      
      
 Doesn't work.
 I tried with an API client/token with all permission but it gives this error:
 
 Status code was 308 and not [201]: HTTP Error 308: Permanent Redirect
 
 If I set a cid it works correctly.

**Comment by redhatrises** [comment]
@TyraelTLK deleting options shouldn't require API client/token access at all, so if you are adding the API Client/Secret tokens just to delete options, try removing them and see what happens.

**Comment by TyraelTLK** [comment]
Hi @redhatrises 

this is what I get without API Client/Secret:

`  "msg": "ERROR executing ['/opt/CrowdStrike/falconctl', '-s', '-f', '--cid=', '--tags=']: OUTPUT = \"\" is not valid value for checksum CID (CCID)\nERROR: failed to process the option --cid\nUsage: falconctl -g GET_OPTIONS\n       falconctl -s [ -f ] SET_OPTIONS\n       falconctl -d [ -f ] DEL_OPTIONS\nwhere GET_OPTIONS := { --cid for CustomerId |\n                       --aid for AgentId |\n                       --apd for App Proxy Disable |\n                       --aph for App Proxy Host |\n                       --app for App Proxy Port |\n                       --rfm-state for indicating whether the sensor is in Reduced Functionality Mode |\n                       --rfm-reason to determine reason for sensor running in Reduced Functionality Mode |\n                       --trace for determining the configured trace level |\n                       --feature to determine the configured sensor feature flags |\n                       --metadata-query to determine the configured sensor cloud provider metadata query flags |\n                       --version for version of sensor currently running |\n                       --message-log for logging messages to disk |\n                       --billing to configure the sensor billing type |\n                       --tags for sensor grouping tags |\n                       --provisioning-token for Provisioning Token |\n                       --systags for system tags currently applied to a running sensor }\nwhere SET_OPTIONS := { --cid=\"{<uuid string>}\" |\n                       --apd=true | --apd=false |\n                       --aph=<app proxy host name> |\n                       --app=<app proxy port> |\n                       --trace=[none|err|warn|info|debug] |\n                       --feature=[none,[enableLog[,disableLogBuffer[,disableOsfm[,emulateUpdate]]]]] |\n                       --metadata-query=[[dis|en]able|[dis|en]ableAWS[,[dis|en]ableAzure[,[dis|en]ableGCP]]] |\n                       --update SIGHUP the sensor for immediate trace/feature update |\n                       --message-log=true | --message-log=false |\n                       --billing=[default|metered] |\n                       --tags=<comma separated list of tags for sensor grouping> (allowed characters: all alphanumerics, '/', '-', '_', and ',') |\n                       --provisioning-token=<provisioning token value> }\nwhere DEL_OPTIONS := { --cid for CustomerId |\n                       --aid for AgentId |\n                       --apd for App Proxy Disable |\n                       --aph for App Proxy Host |\n                       --app for App Proxy Port |\n                       --trace for determining the configured trace level |\n                       --billing to configure the sensor billing type |\n                       --tags for sensor grouping tags |\n                       --provisioning-token for Provisioning Token }\n", `

**Comment by redhatrises** [comment]
@TyraelTLK we found a couple of bugs here that we will be submitting fixes for shortly.
