### ISSUE TITLE
python interpreter changed to python2 for amazon-linux2

### ISSUE THREAD

**Issue by liad5h** [CrowdStrike/ansible_collection_falcon#172]
Hey,

I am installing falcon on an amazon-linux2 machine which does not have python2 installed on it.
The installation completes successfully but the rest of my playbook fails because of a change in the python interpreter in https://github.com/CrowdStrike/ansible_collection_falcon/blob/067e478ee94cc3cd48e847aae0df7620ab23341c/roles/falcon_install/tasks/preinstall.yml#L25

The `when` statement should take into considerations both `ansible_distribution` and `ansible_distribution_major_version` as amazon-linux2 does not need to use python2.

**Comment by redhatrises** [comment]
Hello,

This was more due ansible python version support than amazon linux python version support. It's probably worth another relook since we are now supporting ansible 2.11

**Comment by liad5h** [comment]
Yea, I worked around it for now. just thought it was worth fixing.
