### ISSUE TITLE
Amazon Linux 2 support

### ISSUE THREAD

**Issue by lapkritinis** [CrowdStrike/ansible_collection_falcon#178]
I run a playbook on not-so-old Amazon Linux 2 AMI and got this. Nonetheless I can confirm that I have running falcon agent with manual installation.

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Validate Kernel is Supported] ************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "falcon_sensor_update_kernels_list.json.resources",
    "changed": false,
    "evaluated_to": false,
    "msg": "The kernel version: 5.10.82-83.359.amzn2.x86_64 is not supported by the Falcon Sensor!"
}

PLAY RECAP **********************************************************************************************************************************************************************************

**Comment by redhatrises** [comment]
Are you installing this from Extras? 

FYI. You can disable the check with `falcon_skip_kernel_compat_check` which is defined in https://github.com/CrowdStrike/ansible_collection_falcon/tree/main/roles/falcon_install#role-variables

**Comment by redhatrises** [comment]
Hello,

We have released 3.2.13. Please see if that fixes your issue.

**Comment by carlosmmatos** [comment]
@lapkritinis please confirm wether or not the latest release fixes your issue. Thanks.

**Comment by redhatrises** [comment]
Closing this as there is no further response. Please reopen if needed. Thanks!
