### ISSUE TITLE
Http Error 400: Bad Request: invalid header 

### ISSUE THREAD

**Issue by snarani7** [CrowdStrike/ansible_collection_falcon#18]
Hi shawndwell, 

Need some help, I am trying to download falcon sensor using api but I getting this error with get_url module with headers 
I tired several options to get add accept but nothing is working for me 

fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp/falcon/", "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed", "owner": "root", "response": "HTTP Error 400: Bad Request: invalid header name", "size": 6, "state": "directory", "status_code": 400, "uid": 0, "url": "https://api.crowdstrike.com/sensors/entities/download-installer/v1?id="}

Could you please help me out

**Comment by shawndwells** [comment]
Thanks for reporting this @snarani7 . Paging @redhatrises

**Comment by redhatrises** [comment]
@snarani7 can you provide the version of ansible that you are using and run with the `-vvv` flag set?

**Comment by snarani7** [comment]
Hi redhatrises, 

ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dbadeeds/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
 
when tried to use url instead get_url it is downloading the required package but package is getting corrupted.
 
- name: CrowdStrike Falcon | Download Latest Sensor Installation Package-v1
  uri:
    url: "https://{{ falcon_api_url }}/sensors/entities/download-installer/v1?id={{ falcon_api_sha_hash.json.resources[0].sha256 }}"
    method: GET
    #dest: "/tmp/"
    dest: "{{ falcon_install_tmp_dir }}{{ falcon_api_sha_hash.json.resources[1].name }}"
    checksum: "sha256:{{ falcon_api_sha_hash.json.resources[0].sha256 }}"
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
  register: falcon_sensor_download
  become: true
 
content_disposition": "attachment; filename=falcon-sensor-6.12.0-10912.el8.x86_64.rpm",
"content_type": "application/octet-stream",
"cookies": {},
"date": "Thu, 07 Jan 2021 18:46:01 GMT",
"failed": false,
"gid": 0,
"group": "root",
"mode": "0644",
"msg": "OK (unknown bytes)",
"owner": "root",
"path": "/tmp/falcon-sensor-6.12.0-10912.el8.x86_64.rpm",
s

**Comment by redhatrises** [comment]
@snarani7 the role's minimum ansible version is 2.9 which may be why you are getting a failure getting the ```{{ falcon_api_sha_hash.json.resources[0].sha256 }}``` value.

**Comment by redhatrises** [comment]
Closing as the issue is stale and no further information has been provided to solve the problem. Per the role, the supported ansible version is 2.10
