### ISSUE TITLE
Use this collection without ansible-galaxy

### ISSUE THREAD

**Issue by justinpham-hs** [CrowdStrike/ansible_collection_falcon#181]
Hello!

Was wondering if I can use this ansible collection without using `ansible-galaxy collection install`

Thanks in adv!

**Comment by justinpham-hs** [comment]
Awesome!! Thank you so much! I'll give it a try.

**Comment by carlosmmatos** [comment]
No problems, let me know if it works for you, or if you hit any roadblocks.

**Comment by justinpham-hs** [comment]
Thanks @carlosmmatos ! It worked, but now I'm getting:

```TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Validate Kernel is Supported] ***
Tuesday 07 June 2022  00:23:16 +0000 (0:00:00.443)       0:04:18.187 ********** 
fatal: [ip-****.us-west-*.compute.internal]: FAILED! => 
{
    "assertion": "falcon_sensor_update_kernels_list.json.resources",
    "changed": false,
    "evaluated_to": false,
    "msg": "The kernel version: 4.14.276-211.499.amzn2.x86_64 is not supported by the Falcon Sensor!"
}```

I'm thinking it's a Support ticket to CrowdStrike? 😅

**Comment by justinpham-hs** [comment]
Please feel free to close this issue! Thanks again, much appreciated!

**Comment by carlosmmatos** [comment]
Hi @justinpham-hs,

So we added the capability to let you know if your current configuration of
( kernel + falcon_sensor ) is supported by CS. You can also check out the
new Linux Supported Kernels
<https://falcon.crowdstrike.com/documentation/245/linux-supported-kernels>
support
docs to see what is supported for your kernel version or distro. You can
also opt to skip the kernel compat check in ansible by setting the
following variable: falcon_skip_kernel_compat_check=yes

**Comment by carlosmmatos** [comment]
@justinpham-hs Thanks for reaching out again and glad I was able to help your initial issue. I will close this issue now.
