### ISSUE TITLE
falcon_install failing with kernel version check

### ISSUE THREAD

**Issue by charlesRMD** [CrowdStrike/ansible_collection_falcon#186]
Hi!

I'm trying to install with falcon_install role, but despite the documentation on kernel compatibility stating otherwise ( 5.4.0-113-generic | min version: 6.28.12504 ), i'm getting:

`The sensor version: 6.39.13601 is not supported with kernel: 5.4.0-113-generic`

target machine:
ec2-18-232-176-26.compute-1.amazonaws.com | CHANGED | rc=0 >>
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04

Any help would be appreciated!

Thanks

**Comment by charlesRMD** [comment]
Using the `falcon_skip_kernel_compat_check` I can bypass the error. Still the check is not consistent with the CS documentation

**Comment by charlesRMD** [comment]
Hi 
Thank you.
When I skip the the check, the hosts are in RFM mode status

**Comment by carlosmmatos** [comment]
Okay so I think I see the problem here.. the way we did the kernel compatibility check originally was based on the kernel having a supported Base Package sensor.. in your case, you do not have a supported base package sensor for this kernel which is why it fails, however, there is a ZTL supported sensor version (ie 6.39.13601) which should work. So I need to change the filtering done for the api call, that should let me see both `base_package_supported_sensor_versions` as well as `ztl_supported_sensor_versions` and maybe even `ztl_module_supported_sensor_versions`

**Comment by charlesRMD** [comment]
> Okay so I think I see the problem here.. the way we did the kernel compatibility check originally was based on the kernel having a supported Base Package sensor.. in your case, you do not have a supported base package sensor for this kernel which is why it fails, however, there is a ZTL supported sensor version (ie 6.39.13601) which should work. So I need to change the filtering done for the api call, that should let me see both `base_package_supported_sensor_versions` as well as `ztl_supported_sensor_versions` and maybe even `ztl_module_supported_sensor_versions`

Thanks!. But I'm already installing the  6.39.13601 as you can see in the initial message

**Comment by carlosmmatos** [comment]
> > Okay so I think I see the problem here.. the way we did the kernel compatibility check originally was based on the kernel having a supported Base Package sensor.. in your case, you do not have a supported base package sensor for this kernel which is why it fails, however, there is a ZTL supported sensor version (ie 6.39.13601) which should work. So I need to change the filtering done for the api call, that should let me see both `base_package_supported_sensor_versions` as well as `ztl_supported_sensor_versions` and maybe even `ztl_module_supported_sensor_versions`
> 
> Thanks!. But I'm already installing the 6.39.13601 as you can see in the initial message

Yes but you have 2 issues you have identified here.. 1 is the origin of this issue - which is that the falcon_install role fails when checking for kernel compatibility. That is going to be addressed in an upcoming PR. 

The other issue is that your sensors are in rfm mode - that will need to be addressed with CrowdStrike support. The above command I gave you should give you additional context as to why it's in rfm mode.

**Comment by justinpham-hs** [comment]
Thanks @carlosmmatos !! Will this resolve the error I'm getting as well? 

```
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Validate Kernel is Supported] ***
Wednesday 08 June 2022  17:00:58 +0000 (0:00:00.816)       0:04:36.576 ******** 
fatal: [ip-10-8-29-14.us-west-2.compute.internal]: FAILED! => 
{
    "assertion": "falcon_sensor_update_kernels_list.json.resources",
    "changed": false,
    "evaluated_to": false,
    "msg": "The kernel version: 5.10.112-108.499.amzn2.x86_64 is not supported by the Falcon Sensor!"
}
```

We found that Kernel Comp Check is failing even if the kernel is on the crowdstrike documentation listed as supported.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/76530953/172688347-ea5495d9-b2ba-453a-9f37-046a0ca110c0.png">

**Comment by carlosmmatos** [comment]
> Thanks @carlosmmatos !! Will this resolve the error I'm getting as well?
> 
> ```
> TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Validate Kernel is Supported] ***
> Wednesday 08 June 2022  17:00:58 +0000 (0:00:00.816)       0:04:36.576 ******** 
> fatal: [ip-*-*-*-*.us-west-*.compute.internal]: FAILED! => 
> {
>     "assertion": "falcon_sensor_update_kernels_list.json.resources",
>     "changed": false,
>     "evaluated_to": false,
>     "msg": "The kernel version: 5.10.112-108.499.amzn2.x86_64 is not supported by the Falcon Sensor!"
> }
> ```
> 
> We found that Kernel Comp Check is failing even if the kernel is on the crowdstrike documentation listed as supported.
> 
> <img alt="image" width="1792" src="https://user-images.githubusercontent.com/76530953/172688347-ea5495d9-b2ba-453a-9f37-046a0ca110c0.png">

@justinpham-hs This PR won't fix what you see since your is only supported via the ZTL module supported sensors. I've got a PR in right now #190 to address that and create a new release. So 3.2.13 should work for you. Please re-open an issue if it doesn't work after testing it out.

**Comment by carlosmmatos** [comment]
@charlesRMD  - what is the output of this task:
```shell
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Build Sensor Update Kernels API Query]
```

**Comment by carlosmmatos** [comment]
@charlesRMD, we found the issue. Getting a PR in soon.

**Comment by charlesRMD** [comment]
Thank you @carlosmmatos for your help. In case still needed:
```
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Build Sensor Update Kernels API Query] ****************************************************************************************************************************************************************************************************************
ok: [xxxxxx.compute-1.amazonaws.com]
```

**Comment by carlosmmatos** [comment]
#193 should fix your issue. I'm cutting a new release here shortly for 3.2.14

**Comment by charlesRMD** [comment]
@carlosmmatos 

Thank you!
Tested 3.2.14 and we were able to start deploying on our infra.
