### ISSUE TITLE
Install specific version of daemon

### ISSUE THREAD

**Issue by jlosito** [CrowdStrike/ansible_collection_falcon#207]
Rather than having the `falcon_sensor_version_decrement` variable, I would like to install a specific version of the daemon. A lot of other roles offer this level of control rather than being N-1 from latest.

**Comment by jlosito** [comment]
Hi @carlosmmatos I personally don't need this anymore, hence why I closed it. I figured there's probably other things to tackle. If others want it, that's cool. I'm actually going to make use of the version decrement ability that you've already added.

**Comment by carlosmmatos** [comment]
@jlosito Understood. We do feel like this is something we need to have which is why we re-opened it. We'll have something implemented soon enough for it.
