### ISSUE TITLE
Incorrect Architecture Used

### ISSUE THREAD

**Issue by ia-mfriegang** [CrowdStrike/ansible_collection_falcon#248]
We have been using the install and configure roles for months, and suddenly this week they started throwing errors about the incorrect architecture. I've tried to dig through the role and determine where the architecture gets set, and it seems to me like this may either be an API issue, or something with the Role. We submitted a support ticket, but haven't gotten any help in a few days, so this is my next place to try. Errors we are getting look like this:
 `FAILED! => {"changed": false, "msg": "Wrong architecture 'arm64' -- Run dpkg --add-architecture to add it and update afterwards"}`

It appears that the download URL is determined early on and handled by the API?

Is it possible to use Ansible facts to determine what the architecture is? Whatever mechanism is being used now is causing issues for us

**Comment by carlosmmatos** [comment]
Hi @ia-mfriegang - have you tried using the latest version of the collection v3.2.20? We recently fixed this issue due to an api issue.

**Comment by ia-mfriegang** [comment]
Thanks @carlosmmatos, forcing an update of the collection fixed it for me. All good now!
