### ISSUE TITLE
win install in file mode does not copy the file?

### ISSUE THREAD

**Issue by FlorianHeigl** [CrowdStrike/ansible_collection_falcon#253]
i might be doing something wrong -
but I cannot find _anything_ that would transfer the agent installer file from the control node to the remote system.

is there?

**Comment by carlosmmatos** [comment]
@FlorianHeigl - Check out this discussion [here](https://github.com/CrowdStrike/ansible_collection_falcon/pull/242#issuecomment-1231777236).. let me know if this helps

If this is for windows - then just replace `ansible.builtin.copy` with `ansible.windows.win_copy`

**Comment by carlosmmatos** [comment]
@FlorianHeigl did this help?

**Comment by FlorianHeigl** [comment]
@carlosmmatos hi, I had already hacked in some win_copy usage the night I ran into the issue?
I had to make my install work with ansible 2.9, so it's a bit hard to provide a good-looking PR.

If you want I can provide the right snippet here.

**Comment by carlosmmatos** [comment]
@FlorianHeigl Thanks for the response back. 

You're always more than welcome to submit a PR, but if it's for the functionality of simply copying the installer, then it's not going to get merged in. In that thread above I linked, the reason for this is that we don't want to enforce a method of deployment when using the local file installation option. We're more than happy to install the falcon sensor locally, but it's up to the customer how they would like to get that sensor deployed (ie, via Ansbile copy, NFS, Samba/CIFS, etc). It's easy enough to just add a pre-task to your playbook prior to running the falcon_install role.

**Comment by FlorianHeigl** [comment]
Got it. closing my issue accordingly.
