### ISSUE TITLE
Strange issue with the architecture type of falcon sensor being downloaded via API

### ISSUE THREAD

**Issue by US-Thakur** [CrowdStrike/ansible_collection_falcon#275]
We have been using the install and configure roles of `crowdstrike.falcon-3.2.18` for months, and suddenly this week they started throwing errors about the incorrect architecture.
```
FAILED! => {"changed": false, "msg": "Wrong architecture 'arm64' -- Run dpkg --add-architecture to add it and update afterwards"}
```
Even though this issue seems to be [fixed](https://github.com/CrowdStrike/ansible_collection_falcon/issues/244) in `crowdstrike.falcon-3.2.20` version, strangely I am still facing this issue even after upgrading the falcon collection to 3.2.20 version.
```
(ops_env) [i386][~/ops2/ops/playbooks]$ ansible-galaxy collection list -p ./collections/  | grep crowd
crowdstrike.falcon   3.2.20 
(ops_env) [i386][~/ops2/ops/playbooks]$ 

(ops_env) [i386][~/ops2/ops/playbooks]$ ansible-galaxy collection list  | grep crowd
## No any other copies of the collection on the system.
```
EC2 instance where I am trying to install the falcon:
```
:~# ansible localhost -m setup -a 'gather_subset=!all,!min,os_family'
[WARNING]: No inventory was parsed, only implicit localhost is available
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_distribution": "Ubuntu",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/os-release",
        "ansible_distribution_file_variety": "Debian",
        "ansible_distribution_major_version": "18",
        "ansible_distribution_release": "bionic",
        "ansible_distribution_version": "18.04",
        "ansible_os_family": "Debian",
        "gather_subset": [
            "!all",
            "!min",
            "os_family"
        ],
        "module_setup": true
    },
    "changed": false
}
:~# uname -a
Linux ip-xx-xxx-xxx-xx 5.4.0-1060-aws #63~18.04.1-Ubuntu SMP Mon Nov 15 14:31:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Could we pass the correct architecture type to the collection since it anyway assumes the wrong one during the run?

**Comment by US-Thakur** [comment]
Update:
Looks like the earlier [PR](https://github.com/CrowdStrike/ansible_collection_falcon/pull/243) that fixed the issue reported [here](https://github.com/CrowdStrike/ansible_collection_falcon/issues/244) was incomplete. The new variable `falcon_os_arch` that was added to filter out `arm64` based package should also be added here:
https://github.com/carlosmmatos/ansible_collection_falcon/blob/a6eecef84bdfa19e32cd27b1eb1518f0bfe34ac5/roles/falcon_install/tasks/api.yml#L73

Right now if `falcon_sensor_update_policy_name` is True then the API in next [step](https://github.com/carlosmmatos/ansible_collection_falcon/blob/a6eecef84bdfa19e32cd27b1eb1518f0bfe34ac5/roles/falcon_install/tasks/api.yml#L73) by default returns `arm64` based package since there is no filter being added in the URL.

**Comment by carlosmmatos** [comment]
Looking into this right now. Thanks for bringing it up.

**Comment by US-Thakur** [comment]
@carlosmmatos I raised a PR for this https://github.com/CrowdStrike/ansible_collection_falcon/pull/276
If the issue is valid then please review the PR
