### ISSUE TITLE
CrowdStrike installation fails on x86_64 RHEL7 and RHEL8 since the availability of sensors for s390x

### ISSUE THREAD

**Issue by TyraelTLK** [CrowdStrike/ansible_collection_falcon#278]
Hi,
since yesterday we are no more able to install CrowdStrike on RHEL7 and RHEL8:

"msg": "Cannot add package /tmp/ansible.Kh9nuBfalcon/falcon-sensor-6.49.0-14606.el7.s390x.rpm to transaction. Not a compatible architecture: s390x\nError: Nothing to do\n",

"msg": "Depsolve Error occurred: \n Problem: conflicting requests\n - package falcon-sensor-6.49.0-14606.el8.s390x does not have a compatible architecture\n - nothing provides config(falcon-sensor) = 6.49.0-14606.el8 needed by falcon-sensor-6.49.0-14606.el8.s390x\n - nothing provides libc.so.6(GLIBC_2.2)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x\n - nothing provides libc.so.6(GLIBC_2.2.3)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x\n - nothing provides libdl.so.2(GLIBC_2.2)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x\n - nothing provides libm.so.6(GLIBC_2.2)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x\n - nothing provides libpthread.so.0(GLIBC_2.2)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x\n - nothing provides librt.so.1(GLIBC_2.2)(64bit) needed by falcon-sensor-6.49.0-14606.el8.s390x",

**Comment by carlosmmatos** [comment]
@TyraelTLK This is definitely an issue on the API side.. so it's going to require a similar approach as we did for the arm changes.. I'll try to work on a fix for this asap.

**Comment by anne23** [comment]
In case this helps anyone else while the API fix is on the way, using `falcon_sensor_version_decrement: 1` seems to be a decent workaround.

**Comment by carlosmmatos** [comment]
This should be fixed with the latest PR #281 

If not, please re-open the issue.
