### ISSUE TITLE
`falcon_os_arch_dict` does not take Windows into consideration and causes `roles/falcon_install/tasks/preinstall.yml` to fail

### ISSUE THREAD

**Issue by mfann-or** [CrowdStrike/ansible_collection_falcon#283]
[This commit](https://github.com/CrowdStrike/ansible_collection_falcon/commit/624156a76576052e75b23139a8037ca5574b3c9a) introduced a different way that the `falcon_os_arch` var gets defined, where a dictionary lookup based on the Ansible fact `ansible_architecture` is being performed. But [the dictionary](https://github.com/CrowdStrike/ansible_collection_falcon/commit/624156a76576052e75b23139a8037ca5574b3c9a#diff-044ca520db2535409e37adcb1fca7dfec36988a9b68b0afcbedc8bc25962062bR22) does not take Windows into consideration and fails when `ansible_architecture` returns `64-bit`.

Error:

```json
{
  "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute '64-bit'\n\nThe error appears to be in '/runner/requirements_collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/preinstall.yml': line 32, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"CrowdStrike Falcon | Default Operating System configuration\"\n  ^ here\n",
  "_ansible_no_log": false
}
```

**Comment by carlosmmatos** [comment]
@mfann-or thanks for bringing this up.. Going to be fixing this soon.
