### ISSUE TITLE
CrowdStrike Falcon | Authenticate to CrowdStrike API fails with privilege output closed while waiting for password prompt: /bin/sh: sudo: command not found

### ISSUE THREAD

**Issue by TyraelTLK** [CrowdStrike/ansible_collection_falcon#289]
Hi,
with version 3.2.21 we had the issue with RHEL systems and s390x: https://github.com/CrowdStrike/ansible_collection_falcon/issues/278
That got fixed with 3.2.25 but that version (or one in between) broke our AWX pipeline:

**TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Authenticate to CrowdStrike API] *****
fatal: [ksx-t7-centos7-test1.ourdomain.com -> localhost]: FAILED! => {"msg": "privilege output closed while waiting for password prompt:\n/bin/sh: sudo: command not found\n"}

NO MORE HOSTS LEFT *************************************************************

The issue is present also in 3.2.26

**TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Authenticate to CrowdStrike API] *****  works fine with **3.2.21** (apart the issue on download due s390x...)

**Comment by carlosmmatos** [comment]
@TyraelTLK thanks for opening up the issue. I'll look into this today.

**Comment by carlosmmatos** [comment]
@TyraelTLK The issue you are having is due to the delegation addition that was made on 3.2.24. This was to support the auth task on windows or non-linux systems and to ensure the task is executed on the localhost, not the remote. The updated change to fix this ensures to omit this (which was the default behavior prior to 3.2.24) if the os != linux.

**Comment by TyraelTLK** [comment]
Don't worry, thanks for the quick support!
I confirm that 3.2.27 is working.

Thanks

**Comment by jurschel-gmt** [comment]
This is still a problem when I run this from awx... When I run it locally and become the user that has rights and put in the password it works fine...
