### ISSUE TITLE
Getting "No Falcon Sensor was found!" error on Validate Sensor request

### ISSUE THREAD

**Issue by ktinthecloud** [CrowdStrike/ansible_collection_falcon#292]
Getting the error below when running falcon_install against Windows hosts.  The install works fine when I run it against Ubuntu hosts.

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Validate Sensor request] ****************************************************************************************************************
fatal: [testwin.domain.com]: FAILED! => {"changed": false, "msg": "No Falcon Sensor was found! If passing in falcon_sensor_version, ensure it is correct!"}

**Comment by carlosmmatos** [comment]
@ktinthecloud Thanks for reporting the issue. To better help you, we need some more information. 
- What version of the Ansible collection are you using?
- Can you run it in verbose mode and provide additional logging around the issue?
  - `ansible-playbook -vvv -e "falcon_api_enable_no_log=no" ...`

For this issue, we're interested in seeing what is being returned for the previous steps:
```shell
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Build API Sensor Query] ***
...
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Get list of filtered Falcon sensors] ***
... <scrub sensitive data (ie credentials/bearer token)>
```

**Comment by ktinthecloud** [comment]
crowdstrike.falcon 3.2.27 

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Build API Sensor Query] **********************************************************************************************
task path: /home/user@domain.com/projects/ecco-se-ansible-crowdstrike/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/win_api.yml:35
ok: [testwin.domain.com] => {
    "ansible_facts": {
        "falcon_os_query": "os:\"Windows\"+os_version:\"\"+version:\"6.45.14203\""
    },
    "changed": false
}
Read vars_file 'vault_secrets/secrets_crowdstrike.yml'
Read vars_file 'vault_secrets/secrets_common.yml'

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Get list of filtered Falcon sensors] *********************************************************************************
task path: /home/user@domain.com/projects/ecco-se-ansible-crowdstrike/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/win_api.yml:41
Using module file /home/user@domain.com/projects/ecco-se-ansible-crowdstrike/collections/ansible_collections/ansible/windows/plugins/modules/win_uri.ps1
Pipelining is enabled.
<testwin.domain.com> ESTABLISH WINRM CONNECTION FOR USER: ServiceAcct on PORT 5985 TO testwin.domain.com
EXEC (via pipeline wrapper)
ok: [testwin.domain.com] => {
    "changed": false,
    "character_set": "",
    "connection": "keep-alive",
    "content": "{\n \"meta\": {\n  \"query_time\": 0.079686155,\n  \"powered_by\": \"binserv\",\n  \"trace_id\": \"57120820-eddf-4113-a6fd-6d3257d9827a\"\n },\n \"errors\": [],\n \"resources\": []\n}",
    "content_encoding": "",
    "content_length": "159",
    "content_type": "application/json",
    "cookies": [],
    "date": "Fri, 03 Feb 2023 14:36:41 GMT",
    "elapsed": 0.4218752,
    "headers": [
        "Connection",
        "Strict-Transport-Security",
        "X-Cs-Region",
        "X-Cs-Traceid",
        "X-Ratelimit-Limit",
        "X-Ratelimit-Remaining",
        "Content-Length",
        "Content-Type",
        "Date",
        "Server"
    ],
    "invocation": {
        "module_args": {
            "body": null,
            "client_cert": null,
            "client_cert_password": null,
            "content_type": null,
            "creates": null,
            "dest": null,
            "follow_redirects": "safe",
            "force_basic_auth": false,
            "headers": {
                "Content-Type": "application/json",
                "authorization": "Bearer --REDACTED--
            },
            "http_agent": "ansible-httpget",
            "maximum_redirection": 50,
            "method": "GET",
            "proxy_password": null,
            "proxy_url": null,
            "proxy_use_default_credential": false,
            "proxy_username": null,
            "removes": null,
            "return_content": true,
            "status_code": [
                200
            ],
            "url": "https://api.us-2.crowdstrike.com/sensors/combined/installers/v1?filter=os%3A%22Windows%22%2Bos_version%3A%22%22%2Bversion%3A%226.45.14203%22",
            "url_method": "GET",
            "url_password": null,
            "url_timeout": 30,
            "url_username": null,
            "use_default_credential": false,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "is_from_cache": false,
    "is_mutually_authenticated": false,
    "json": {
        "errors": [],
        "meta": {
            "powered_by": "binserv",
            "query_time": 0.079686155,
            "trace_id": "57120820-eddf-4113-a6fd-6d3257d9827a"
        },
        "resources": []
    },
    "last_modified": "2023-02-03T06:36:41.2540576-08:00",
    "method": "GET",
    "msg": "OK",
    "protocol_version": {
        "Build": -1,
        "Major": 1,
        "MajorRevision": -1,
        "Minor": 1,
        "MinorRevision": -1,
        "Revision": -1
    },
    "response_uri": "https://api.us-2.crowdstrike.com/sensors/combined/installers/v1?filter=os%3A%22Windows%22%2Bos_version%3A%22%22%2Bversion%3A%226.45.14203%22",
    "server": "nginx",
    "status_code": 200,
    "status_description": "OK",
    "strict_transport_security": "max-age=15724800; includeSubDomains,max-age=31536000; includeSubDomains",
    "supports_headers": true,
    "url": "https://api.us-2.crowdstrike.com/sensors/combined/installers/v1?filter=os%3A%22Windows%22%2Bos_version%3A%22%22%2Bversion%3A%226.45.14203%22",
    "x_cs_region": "us-2",
    "x_cs_traceid": "57120820-eddf-4113-a6fd-6d3257d9827a",
    "x_ratelimit_limit": "6000",
    "x_ratelimit_remaining": "5999"
}
Read vars_file 'vault_secrets/secrets_crowdstrike.yml'
Read vars_file 'vault_secrets/secrets_common.yml'

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Validate Sensor request] *********************************************************************************************
task path: /home/user@domain.com/projects/ecco-se-ansible-crowdstrike/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/win_api.yml:52
fatal: [testwin.domain.com]: FAILED! => {
    "changed": false,
    "msg": "No Falcon Sensor was found! If passing in falcon_sensor_version, ensure it is correct!"
}

PLAY RECAP **************************************************************************************************************************************************************************
testwin.domain.com : ok=12   changed=0    unreachable=0    failed=1    skipped=22   rescued=0    ignored=0

**Comment by carlosmmatos** [comment]
This is probably because that version (`6.45.14203`) doesn't seem to exist for Windows.

**Comment by ktinthecloud** [comment]
Why is it trying to install that version then?

**Comment by ktinthecloud** [comment]
Never mind, I had it hardcoded.

**Comment by ktinthecloud** [comment]
Thanks for the help @carlosmmatos
