### ISSUE TITLE
Cannot install on x86_64 architecture anymore

### ISSUE THREAD

**Issue by neilschelly** [CrowdStrike/ansible_collection_falcon#296]
The changes introduced with https://github.com/CrowdStrike/ansible_collection_falcon/issues/278 have now caused it to start failing x86_64 package installations. It attempts to install the arm64 package instead.

I commented where I see the typo here:
https://github.com/CrowdStrike/ansible_collection_falcon/commit/624156a76576052e75b23139a8037ca5574b3c9a#r99871580

The output from the ansible run is:
```
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Validate Kernel is Supported] *******************************************************************************************************************************************************
fatal: [che-perforcetest]: FAILED! => {
    "assertion": "falcon_sensor_update_kernels_list.json.resources",
    "changed": false,
    "evaluated_to": false,
    "msg": "The kernel version: 5.15.0-60-generic is not supported by the Falcon Sensor!"
}
```

Upon closer inspection, you can see that the package attempting to be installed is:
```
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Set full file download path] ***********************************************************************************************************************************************************************************************************************************
task path: /home/nschelly/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/api.yml:143
ok: [che-perforcetest] => {
    "ansible_facts": {
        "falcon_sensor_pkg": "/tmp/ansible.x4vnky_3falcon/falcon-sensor_6.50.0-14712_arm64.deb"
    },
    "changed": false
}
```

To be clear, `ansible_architecture` on this machine is `x86_64`.

**Comment by carlosmmatos** [comment]
Hi @neilschelly - thanks for opening up an issue.

I responded to your comment, it's not a typo. It's excluding arm and s390 from the api results. This is because the API does not return a proper architecture field, instead it does it by adding the non-x86_64 architectures to the name:

Example for RHEL 8
```
For x86_64
"os_version": "8"

For arm
"os_version": "8 - arm64"
```

So you can see that we can't just say - give me only x86_64 since that doesn't exist.

Can you provide me with the output from the following task:
`TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Determine Operating System Architecture (Linux)] ***`

**Comment by neilschelly** [comment]
Okay, please disregard that comment and this issue then. I am seeing this behavior, but I don't have an explanation yet. I jumped to the wrong conclusion, and it doesn't even apply the version of the crowdstrike.falcon collection I'm using. I'd forgotten that I had that pinned at an old release.

I will start by upgrading to the latest collection and go from there. Sorry for the noise...

**Comment by carlosmmatos** [comment]
No worries, and if you have any issues with the latest collection please feel free to open another issue up.
