### ISSUE TITLE
RPM install fails on RHEL/Rocky/AlmaLinux >=8 with FIPS enabled

### ISSUE THREAD

**Issue by tjmullicani** [CrowdStrike/ansible_collection_falcon#297]
## Problem
Attempting to install any of the CrowdStrike Falcon RPMs on a RedHat Linux-based operating system running >8 with FIPS enabled will fail with the following error:
```bash
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Install Falcon Sensor Package (Linux)] ***********
Wednesday 08 February 2023  21:23:09 +0000 (0:00:00.091)       0:01:19.312 **** 
fatal: [<redacted>]: FAILED! => changed=false 
  ansible_facts:
    discovered_interpreter_python: /usr/libexec/platform-python
  failures: []
  msg: |-
    Unknown Error occured: Transaction test error:
      package falcon-sensor-6.49.0-14604.el8.x86_64 does not verify: no digest
  rc: 1
  results: []
```

### Resolution
There are several solutions:
* Sign RPMs with SHA256 (example is at https://www.starlab.io/blog/adding-sha256-digests-to-rpms)
* Have package rebuilt with rpm >= 4.14
* Disable FIPS
* Use workaround when FIPS is enabled
```bash
#  rpm -ivh --nodigest --nofiledigest <RPM>
```

### Root Cause
* FIPS mode is enabled
* This is related to the changes mentioned in the RHEL8.0 [release notes](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index)
* RPM now validates the entire package contents before starting an installation
* On Red Hat Enterprise Linux 7, the RPM utility verified payload contents of individual files while unpacking. However, this is insufficient for multiple reasons:
```
    If the payload is damaged, it is only noticed after executing script actions, which are irreversible.
    If the payload is damaged, upgrade of a package aborts after replacing some files of the previous version, which breaks a working installation.
    The hashes on individual files are performed on uncompressed data, which makes RPM vulnerable to decompressor vulnerabilities.
```
* On Red Hat Enterprise Linux 8, the entire package is validated prior to the installation in a separate step, using the best available hash.
* Packages built on Red Hat Enterprise Linux 8 use a new SHA-256 hash on the compressed payload. On signed packages, the payload hash is additionally protected by the signature, and thus cannot be altered without breaking a signature and other hashes on the package header. Older packages use the MD5 hash of the header and payload unless it is disabled by configuration.
* The %_pkgverify_level macro can be used to additionally enable enforcing signature verification before installation or disable the payload verification completely. In addition, the %_pkgverify_flags macro can be used to limit which hashes and signatures are allowed. For example, it is possible to disable the use of the weak MD5 hash at the cost of compatibility with older packages.
* Packages need to be built with rpm >= 4.14 in order to be installable in FIPS mode, the key being the new SHA256 digest on the compressed payload.

**Comment by tjmullicani** [comment]
A temporary workaround is to run the `rpm -ivh --nodigest --nofiledigest <falcon-xxx.rpm>` command, but the long-term solution is to re-sign the RPMs using SHA256.

**Comment by tjmullicani** [comment]
Here is a real-world example of another project dealing with this same issue: https://github.com/grafana/grafana/issues/41036

**Comment by tjmullicani** [comment]
Another temporary workaround is to run the following before Ansible (this lowers the RPM signature checking requirements, which poses a security risk):
```bash
echo "%_pkgverify_level signature" >/etc/rpm/macros.verify
```

and then remove the file after the role execution is complete:
```bash
rm -f /etc/rpm/macros.verify
```

**Comment by carlosmmatos** [comment]
@tjmullicani Thanks for opening the issue.. This is definitely an issue that needs to be opened with CrowdStrike support to get an actual fix (sign rpm with sha256).

As for workarounds - if this was something that affected all linux based operating systems I would be more inclined to include one to the install role. However, I think it's easy enough to implement a workaround in a playbook that tries to install the crowdstrike package. 

Let me double check on our side if there has been any movement on this front, and what the recommended steps that we have given customers are. After that, we can re-evaluate where we want to go.

**Comment by carlosmmatos** [comment]
@tjmullicani Based on our latest release notes:
https://falcon.crowdstrike.com/support/news/release-notes-falcon-sensor-for-linux-6-50-14712

It looks like we added support for FIPS. Can you verify please?

**Comment by tjmullicani** [comment]
> @tjmullicani Based on our latest release notes: https://falcon.crowdstrike.com/support/news/release-notes-falcon-sensor-for-linux-6-50-14712
> 
> It looks like we added support for FIPS. Can you verify please?

It looks like the latest RPM release fixed it. I originally had falcon_sensor_version_decrement set to 1, and the older releases are still missing the SHA256 signature.

**Comment by carlosmmatos** [comment]
Closing this issue since the latest sensor release supports FIPS.
