### ISSUE TITLE
Ansible variable errors with INJECT_FACTS_AS_VARS False

### ISSUE THREAD

**Issue by tjmullicani** [CrowdStrike/ansible_collection_falcon#298]
If ansible.cfg is configured to set [INJECT_FACTS_AS_VARS](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#inject-facts-as-vars) to False, you will get several "variable xxx is undefined" error messages. A solution in this case is to convert the ansible_* variables (such as ansible_kernel, ansible_pkg_mgr, etc) to  ansible_facts (e.g., ansible_facts['kernel'], ansible_facts['pkg_mgr']). See [reference 1](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html#ansible-facts) and [reference 2](https://stackoverflow.com/a/73859985).

```bash
fatal: [<redacted>]: FAILED! => 
  msg: |-
    The conditional check 'ansible_pkg_mgr in rpm_packagers' failed. The error was: error while evaluating conditional (ansible_pkg_mgr in rpm_packagers): 'ansible_pkg_mgr' is undefined
  
    The error appears to be in '/root/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/install.yml': line 17, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: CrowdStrike Falcon | Import CrowdStrike Falcon RPM GPG key from file
      ^ here
```

**Comment by tjmullicani** [comment]
I can work on a merge request in the next few days, if needed.

**Comment by carlosmmatos** [comment]
@tjmullicani Good find. Seems to be something that will eventually become set to false by default down the road due to potential name collisions from modules. I'll go through the existing vars that need to be updated and have you review the PR!

**Comment by carlosmmatos** [comment]
@tjmullicani Give the PR a review when you get a chance. Thanks.
