### ISSUE TITLE
Windows configuration does not support sensor tagging

### ISSUE THREAD

**Issue by clrosier** [CrowdStrike/ansible_collection_falcon#303]
Hello awesome maintainers!

I was wondering if there was a way I could pass in tags for the win_configure.yml file in the configuration role.  Currently we tag our 
assets based on inventory tags from aws and it's working well for our linux hosts.  For our windows hosts however, we currently have to manually assign tags.

Is there an ansible way to do this currently?

**Comment by carlosmmatos** [comment]
Hi @clrosier  - currently Sensor tags for Windows hosts are assignable during installation.

So you could do something like:
```yaml
falcon_windows_install_args: "/norestart GROUPING_TAGS=tag1,tag2"
```

For sensor versions >+ 6.42 - you can refer to the [Falcon Docs](https://falcon.crowdstrike.com/documentation/23/falcon-sensor-for-windows#managing-sensor-grouping-tags) to see how to use the `CsSensorSettings` utility.

At some point we will probably add support for the `CsSensorSettings` utility in the falcon_configure role.

**Comment by clrosier** [comment]
Ah I see, so if I already have the sensor installed on windows hosts, I would need to uninstall the sensor and reinstall with the falcon_windows_install_args variable set like above?

Thanks Carlos!

**Comment by carlosmmatos** [comment]
Depends on the version of the sensor you have installed.. If it's 6.42+ then there is a utility you could use called CsSensorSettings. You could test it out by doing the following:

```yaml
- name: Test running the CsSensorSettings command
  ansible.windows.win_command: '"C:\Program Files\CrowdStrike\CsSensorSettings" --version'
```

If that succeeds, then you can use that to set tags. Just follow the Falcon docs I linked above for examples.

**Comment by clrosier** [comment]
Awesome, thank you I really appreciate the prompt responses.  I should be able to work through my problems now.
