### ISSUE TITLE
Incorrect conditonal causing `win_auth.yml` to fail

### ISSUE THREAD

**Issue by mfann-or** [CrowdStrike/ansible_collection_falcon#315]
The conditional in the jinja [here](https://github.com/CrowdStrike/ansible_collection_falcon/blob/808ca69be6815a2503af2a902bece60049c58416/roles/falcon_install/tasks/win_auth.yml#L44) is causing the [CrowdStrike Falcon | Detect Target CID Based on Credentials](https://github.com/CrowdStrike/ansible_collection_falcon/blob/main/roles/falcon_install/tasks/win_auth.yml#L50) task to fail.

This is because the conditional is setting the `falcon_api_oauth2_token` to the value from `falcon_api_oauth2_token_win_redirect` even when the task is skipped.

More specifically, the conditional `falcon_api_oauth2_token_win_redirect | length > 0` is incorrect since the registered value from `falcon_api_oauth2_token_win_redirect` comes back as a dict object where the length filter returns `3`.

**Comment by carlosmmatos** [comment]
@mfann-or will look into it today. Thanks for bringing it up
