### ISSUE TITLE
falcon_sensor_version_decrement is not working as documented

### ISSUE THREAD

**Issue by dpzx** [CrowdStrike/ansible_collection_falcon#323]
crowdstrike.falcon 3.2.31

Document states that:

falcon_sensor_version_decrement - Sensor N-x version to install (int, default: 0 [latest])

values set with version: the version is not in any order
0 = 6.51.14812  
1 = 6.48.14511
2 = 6.49.14611
3 = 6.50.14713
4 = 6.46.14306
5 = 6.48.14504

**Comment by carlosmmatos** [comment]
@dpzx thank you for opening up this issue.. looking into this today.
