### ISSUE TITLE
two api return unmatched version

### ISSUE THREAD

**Issue by kiyor-cai-exa** [CrowdStrike/ansible_collection_falcon#324]
`Validate Sensor version is compatible with Kernel` task get flowing error
`The sensor version: 6.48.14511 is not supported with kernel: 3.10.0-957.21.2.el7.x86_64`

debug found two api return unmatched version of app

`https://api.crowdstrike.com/sensors/combined/installers/v1?filter=os%3A%22RHEL/CentOS/Oracle%22%2Bos_version%3A%227%22`
got
{
    "description": "Falcon Kernel Sensor for RHEL/CentOS/Oracle 7",
    "file_size": 35952408,
    "file_type": "rpm",
    **"name": "falcon-sensor-6.48.0-14511.el7.x86_64.rpm",**
    "os": "RHEL/CentOS/Oracle",
    "os_version": "7",
    "platform": "linux",
    **"release_date": "2023-03-13T22:22:24.467Z",**
    "sha256": "ca2c95733617eef4a4550dfb8299328263939e9f9867cfaa659ea9e2c2a3cf43",
    **"version": "6.48.14511"**
}

`https://api.crowdstrike.com/policy/combined/sensor-update-kernels/v1?filter=vendor%3A%22redhat%22%2Brelease%3A%223.10.0-957.5.1.el7.x86_64%22`
got
"6.46.14306",
"6.47.14408",
**"6.48.14504",**
"6.49.14604",
"6.49.14611",

**"modified_timestamp": "2022-01-07 23:53:04",**

**Comment by carlosmmatos** [comment]
@kiyor-cai-exa Are you still having any issues?

**Comment by kiyor-cai-exa** [comment]
looks no issue now, can be close
