### ISSUE TITLE
falcon_cid being cut off because of a dash

### ISSUE THREAD

**Issue by joshb89** [CrowdStrike/ansible_collection_falcon#326]
I'm running in to an issue with the install/configure tasks relegated to the falcon_cid value. Our CID has a dash in it and on execution, the dash and everything after it is cut off. I tried to use single and double quotes around it to no success. What can I do to ensure the entire CID gets passed to systems?

**Comment by carlosmmatos** [comment]
Hey @joshb89 - What is the error you are having? Does the falcon_configure role fail when setting the `falcon_cid` option?
