### ISSUE TITLE
Getting a version not found error when specifying a specific sensor version

### ISSUE THREAD

**Issue by clrosier** [CrowdStrike/ansible_collection_falcon#327]
Not sure if I am missing some sort of configuration or this is intended behaviour, but with recent updates to the role, I am now getting this error when trying to specify a pinned sensor version: (Note I renamed the role locally)

`
TASK [app_falcon_sensor : CrowdStrike Falcon | Validate Sensor request] *************************************************************************************************************************************************
fatal: [10.20.4.202]: FAILED! => {
    "changed": false,
    "msg": "No Falcon Sensor was found! If passing in falcon_sensor_version, ensure it is correct!"
}
`
Everything is OK is I allow it to pick the latest.

In order to try to triage the issue I attempted to print out the list of falcon versions being pulled from the API, but it seems like no versions get found and that is why the task cannot install the specified version.

Any ideas?  Thanks!

**Comment by carlosmmatos** [comment]
Hey @clrosier - thanks for opening up an issue. Can you run this in verbose mode so that I can see the query that was run, or provide me with the output. This is the particular task I'm looking for:
```sh
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Build API Sensor Query (Linux)] 
```

**Comment by carlosmmatos** [comment]
@clrosier it looks like that sensor version is not a valid version. For example, if I run that query, and remove the version from it to get a list of supported versions, this is the top 2 results:
```json
    "resources": [
        {
            "name": "falcon-sensor_6.51.0-14812_amd64.deb",
            "description": "Falcon Kernel Sensor for Ubuntu 16.04LTS, 18.04LTS, and 20.04LTS",
            "platform": "linux",
            "os": "Ubuntu",
            "os_version": "16/18/20/22",
            "sha256": "d792dfb2d3252be684bb04b34949a91da5de3ff6f87f672452e8d1a607a7af31",
            "release_date": "2023-03-16T22:41:16.607Z",
            "version": "6.51.14812",
            "file_size": 39990048,
            "file_type": "deb"
        },
        {
            "name": "falcon-sensor_6.50.0-14713_amd64.deb",
            "description": "Falcon Kernel Sensor for Ubuntu 16.04LTS, 18.04LTS, and 20.04LTS",
            "platform": "linux",
            "os": "Ubuntu",
            "os_version": "16/18/20/22",
            "sha256": "faf00ab6917e8ea4094b4a4ff79a60b8b1f5bddc11dc08248344b17ba85adb3c",
            "release_date": "2023-02-08T23:29:54.457Z",
            "version": "6.50.14713",
            "file_size": 38201540,
            "file_type": "deb"
        },
```

Out of curiosity, where did you get this sensor version from that you are using? 

Also, if you would like to debug this on the Ansible side to see the list of available sensors for your OS, I would omit `falcon_sensor_version` and run the playbook like so:
```shell
ansible-playbook falcon_install.yml -vvv -e "falcon_api_enable_no_log=no"
```

You would want to look at the output from the following task:
```
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Get list of filtered Falcon sensors]
```

**Comment by carlosmmatos** [comment]
@clrosier Just checking in to see if you are still have any issues/concerns around this?
