### ISSUE TITLE
Installer playbook fatal errors on older version without bypass ability

### ISSUE THREAD

**Issue by jhawkwind** [CrowdStrike/ansible_collection_falcon#329]
When the console's sensor update policy is set to a version newer (early adopter version) than on the playbooks' default (latest version), the playbooks fatal errors on the step "CrowdStrike Falcon | Install Falcon Sensor Package"

The proper behavior should be that if a version is not specified and an update policy is not specified and a client is already installed, one of three things must be possible to ensure idempotency:
1. Permit a newer version of the client exists via a flag to be set to "ignore_error".
2. Read the sensor asset inventory and determine it's assigned sensor group's update policy and ensure it matches; and re-install the correct version.
3. Permit the setting of using the "Early Adopter" version.

**Comment by carlosmmatos** [comment]
@jhawkwind Thanks for opening up an issue. Let me look into this.

**Comment by carlosmmatos** [comment]
Okay so did a few tests just to make sure we support Early Adopt via sensor update policies and the answer is yes. That is working fine on my tests. Unfortunately it looks like the current Early Adopter build coincides with the latest sensor build so trying to match your scenario doesn't match 1:1.. A few things to talk about:

1. Can you provide the exact error you are getting for the `CrowdStrike Falcon | Install Falcon Sensor Package` task?
    1. Allowing an upgrade of a package to be installed is default behavior and works fine from testing. However downgrading is not currently configured.
1. When you say "Read the sensor asset inventory".. are you asking if we could dynamically pull your falcon hosts metadata from the API to see if there is a sensor update policy associated to it?
    1. If so, I think there are a few ways we can work towards this, and perhaps one way that you can use now to work with this: 
        1. We have been discussing the idea of developing inventory plugins, which would be very useful when managing existing hosts with the falcon-sensor installed. We have also talked about introducing an inventory plugin that can also show unmanaged hosts (those that don't have the sensor installed) as well.
        2. We're also in the works of creating a more API centric collection, that would allow us to use our existing APIs to provide much more flexibility than simple install/configure.
        3. Finally, for now, you could make use of hostgroups in your inventory file. Assuming that your sensor update policies have some form of host group association already, you could translate those into your Ansible inventory file. For example:
```ini
[linux-prod]
prod-*.example.com

[linux-dev]
dev-*.example.com

[linux-prod:vars]
falcon_sensor_update_policy_name="Prod Update Policy"
...

[linux-dev:vars]
falcon_sensor_update_policy_name="Early Adopter Policy"
...
```

3. To follow onto your 3rd response, we allow you to pass and use the name of a sensor update policy, which is currently how one would identify Early Adopter builds.

**Comment by jhawkwind** [comment]
Specifically this task: "CrowdStrike Falcon | Install Falcon Sensor Package (Linux)"

The error is: "A later version is already installed"
