### ISSUE TITLE
Python Install Version Challenges

### ISSUE THREAD

**Issue by professor-panda** [CrowdStrike/ansible_collection_falcon#335]
I am installing Falcon on a new AWS linux image and Python2 is not present in the image any more. How do i tell the playbook to use the dnf module install instead of yum to use Python3? 

fatal: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "autoremove": false,
            "bugfix": false,
            "conf_file": null,
            "disable_excludes": null,
            "disable_gpg_check": false,
            "disable_plugin": [],
            "disablerepo": [],
            "download_dir": null,
            "download_only": false,
            "enable_plugin": [],
            "enablerepo": [],
            "exclude": [],
            "install_repoquery": true,
            "install_weak_deps": true,
            "installroot": "/",
            "list": null,
            "lock_timeout": 30,
            "name": [
                "/tmp/ansible.8o2v769_falcon/falcon-sensor-6.51.0-14812.amzn2.x86_64.rpm"
            ],
            "releasever": null,
            "security": false,
            "skip_broken": false,
            "state": "present",
            "update_cache": false,
            "update_only": false,
            "use_backend": "auto",
            "validate_certs": true
        }
    },
    "msg": "The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.. The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."
}

**Comment by carlosmmatos** [comment]
@professor-panda Thanks for opening up the issue. I've seen this issue pop up before with Amazon Linux instances #172 and there's not much to do but to change the `ansible_python_interpreter`. Just out of curiosity, is DNF installed on your Amazon Linux 2 host (`$ which dnf`)?

Also, when you say python2 is not present in the image anymore, are you saying that you have manually removed it? Just trying to get a little more info.

Here are some similar scenarios:
https://github.com/ansible/ansible/issues/32532
http://www.freekb.net/Article?id=4400
https://stackoverflow.com/questions/62100869/ansible-error-the-python-2-bindings-for-rpm-are-needed-for-this-module

**Comment by carlosmmatos** [comment]
@professor-panda was this resolved?

**Comment by professor-panda** [comment]
@carlosmmatos sorry for the late reply. Here is the details.  

Using https://aws.amazon.com/linux/amazon-linux-2023

And DNF is present under /usr/bin/dnf

Python2 is not present in this image.  Python3 is Python 3.9.16.

**Comment by carlosmmatos** [comment]
Ahh okay.. well firstly, we don't support amazon 2022+ yet. You can see a previous #336 where it was brought up. However, it seems that the user does not experience the same issue you are, so I will at least double check and run against a 2023 image just to make sure there isn't some weird python'ism happening.

**Comment by professor-panda** [comment]
@carlosmmatos do you know when support for 2022+ will come out?

**Comment by carlosmmatos** [comment]
@professor-panda There is nothing official as of yet. I would stay tuned to the Support KBs for supported OS's. From what I've gathered, it's being worked on as fast as possible since it's a big part of our Linux base.

**Comment by carlosmmatos** [comment]
@professor-panda btw I just got around to testing the python issue you were seeing. I just spun up an amazon 2023 instance and ran the following:
```
❯ ansible -i tests/inventory amz-2023 -m ping
[WARNING]: Platform linux on host amz-2023 is using the discovered Python interpreter at /usr/bin/python3.9, but future installation of another Python interpreter could change the meaning
of that path. See https://docs.ansible.com/ansible-core/2.12/reference_appendices/interpreter_discovery.html for more information.
amz-2023 | SUCCESS => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3.9"
    },
    "changed": false,
    "ping": "pong"
}
```
I don't see any issues here.

Running the falcon_install role against that host - I get to the install step and it fails due a dependency issue, no issues with yum/dnf module itself. This is to be expected as this sensor is not meant for this distro. So I'm not sure why you were seeing any issues around dnf python issues.

**Comment by professor-panda** [comment]
I am not sure either. I will do more testing and see if i find anything. 

I think we can close this for now. But wanted to document incase others get here. For now i am using older ami's which works.
