### ISSUE TITLE
Install fails on new Amazon Linux versions

### ISSUE THREAD

**Issue by frankbranham** [CrowdStrike/ansible_collection_falcon#336]
Amazon changed their distribution major number to a yearly release. 

Now you have 2, 2022, and 2023 to deal with. 

 "ansible_distribution": "Amazon",
        "ansible_distribution_file_parsed": true,
        "ansible_distribution_file_path": "/etc/os-release",
        "ansible_distribution_file_variety": "Amazon",
        "ansible_distribution_major_version": "2022",
        "ansible_distribution_minor_version": "NA",
        "ansible_distribution_release": "NA",
        "ansible_distribution_version": "2022",
        
        (/etc/os_release)
        NAME="Amazon Linux"
VERSION="2022"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2022"
PLATFORM_ID="platform:al2022"
PRETTY_NAME="Amazon Linux 2022"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2022"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2022"
SUPPORT_END="2027-11-01"

**Comment by frankbranham** [comment]
Execution:
TASK [crowdstrike.falcon_install : CrowdStrike Falcon | Build API Sensor Query (Linux)] *******************************************************************************************
ok: [localhost] => {"ansible_facts": {"falcon_os_query": "os:\"Amazon Linux\"+os_version:\"*2022*\"+os_version:!~\"arm64\"+os_version:!~\"zLinux\""}, "changed": false}

TASK [crowdstrike.falcon_install : CrowdStrike Falcon | Get list of filtered Falcon sensors] **************************************************************************************
ok: [localhost] => {"changed": false, "connection": "close", "content": "{\n \"meta\": {\n  \"query_time\": 0.113789906,\n  \"powered_by\": \"binserv\",\n  \"trace_id\": \"fb03daa4-c285-42c3-bfc5-1562af1c9ebd\"\n },\n \"errors\": [],\n \"resources\": []\n}", "content_length": "159", "content_type": "application/json", "cookies": {}, "cookies_string": "", "date": "Thu, 13 Apr 2023 14:45:58 GMT", "elapsed": 0, "json": {"errors": [], "meta": {"powered_by": "binserv", "query_time": 0.113789906, "trace_id": "fb03daa4-c285-42c3-bfc5-1562af1c9ebd"}, "resources": []}, "msg": "OK (159 bytes)", "redirected": false, "server": "nginx", "status": 200, "strict_transport_security": "max-age=15724800; includeSubDomains, max-age=31536000; includeSubDomains", "url": "https://api.crowdstrike.com/sensors/combined/installers/v1?sort=version|desc&filter=os%3A%22Amazon%20Linux%22%2Bos_version%3A%22%2A2022%2A%22%2Bos_version%3A%21~%22arm64%22%2Bos_version%3A%21~%22zLinux%22", "x_cs_region": "us-1", "x_cs_traceid": "fb03daa4-c285-42c3-bfc5-1562af1c9ebd", "x_ratelimit_limit": "6000", "x_ratelimit_remaining": "5999"}

TASK [crowdstrike.falcon_install : CrowdStrike Falcon | Validate Sensor request] **************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No Falcon Sensor was found! If passing in falcon_sensor_version, ensure it is correct!"}

**Comment by carlosmmatos** [comment]
@frankbranham Thanks for bringing it up.

<insert angry fist at amazon!> Will try to get this fixed soon

**Comment by carlosmmatos** [comment]
@frankbranham So it looks like we don't currently support 2022/2023 Amazon Linux yet. So unfortunately there is not much we can do on here until our sensor supports it.

**Comment by frankbranham** [comment]
That seems a little odd. I can understand not supporting 2023 yet (it uses a 6.1 linux kernel). 2022 still has a 5.10 kernel and is basically amazon linux 2 with the new naming scheme.

**Comment by carlosmmatos** [comment]
It's because 2022+ are based on Fedora. The same reason we don't support CentOS streams and Fedora now is what you are seeing with Amazon Linux 2022+.. It is in the works though.
