### ISSUE TITLE
Uninstall - Win Error

### ISSUE THREAD

**Issue by txsastre** [CrowdStrike/ansible_collection_falcon#379]
hello

I tried to uninstall crowdstrike from windows and I'm getting this error. also the crowdstrike is not uninstalled

the playbook is quite simple

```
---
- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_uninstall
```

The error:

```
TASK [crowdstrike.falcon.falcon_uninstall : CrowdStrike Falcon | Remove Falcon Sensor (Windows)] **************************************************************************************************************
fatal: [10.101.137.20]: FAILED! => {"changed": false, "msg": "unexpected rc from '\"C:\\ProgramData\\Package Cache\\{8fc42182-d5f1-492c-a5ff-f155cc0a7816}\\WindowsSensor.LionLanner.exe\" /uninstall /quiet /norestart': see rc, stdout, and stderr for more details", "rc": 1605, "reboot_required": false, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

**Comment by txsastre** [comment]
Well... I tried again, and the error has disappeared.

**Comment by txsastre** [comment]
also if I try to remove from the server I get this error

![imatge](https://github.com/CrowdStrike/ansible_collection_falcon/assets/10468371/e27a5cd4-d9c3-49f9-a649-7cc4d2c368d9)

**Comment by carlosmmatos** [comment]
@txsastre Do you know if you have maintenance tokens enabled to prevent uninstalls? I think you are going to have to reach out to support to help with this because the sensor may be in a funky state. Check out this [support article](https://supportportal.crowdstrike.com/s/article/ka16T000000wtekQAA)

**Comment by txsastre** [comment]
yes I'm going to try to find out.

by the way I have done some more test, I cloned 2 widnows 2019, uninstall works in 1 of 3, also uninstals works on a windows 2012.

playbook used, same as example [](https://github.com/CrowdStrike/ansible_collection_falcon/tree/main/roles/falcon_uninstall)

```
---
- hosts: all
  roles:
  - role: crowdstrike.falcon.falcon_uninstall

      vars:
      ansible_become_method: runas  
```
error log

```
fatal: [192.168.70.161]: 
FAILED! => {"changed": 
false, "msg": "unexpected rc 
from '\"C:\\ProgramData\\Package Cache\\{9c135872-ac27-49d7-b96b-8ba5752470e3}\\WindowsSensor.LionLanner.exe\" /uninstall /quiet /norestart': 
see rc, stdout, and stderr for more details", "rc": 106, "reboot_required": false, "stderr": "", 
"stderr_lines": [], "stdout": "", "stdout_lines": []}
```

**Comment by carlosmmatos** [comment]
Closing for now. Hopefully you opened a support ticket and are working it with them by now.

**Comment by txsastre** [comment]
Sorry for my delay.
The "problem" was that. I needed a different token to uninstall, so there was not a real problem.
Thanks for your help.
