### ISSUE TITLE
Uninstall role also to remove nodes from console

### ISSUE THREAD

**Issue by pblanarik** [CrowdStrike/ansible_collection_falcon#380]
Is it possible to enhance uninstall role so it can also remove nodes from crowdstrike console after agent is uninstalled?

**Comment by carlosmmatos** [comment]
@pblanarik Thanks for opening up the issue. The answer is yes, we can definitely do that and had plans on implementing it.

**Comment by pblanarik** [comment]
Tested and working. Looking forward for ansible galaxy collection release ;-) Thank You.
