### ISSUE TITLE
Installation fails on Ubuntu 22.04 with ansible.legacy.apt parameter 'allow_downgrade'

### ISSUE THREAD

**Issue by mstyne** [CrowdStrike/ansible_collection_falcon#385]
With

`crowdstrike.falcon:3.3.0`
`community.general:7.3.0`

Appears to be similar to #343.

```
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Install Falcon Sensor Package (Linux)] ************************************************************************************************
fatal: [metrics.nyc1.do.xxx.com]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.apt) module: allow_downgrade. Supported parameters include: update_cache (update-cache), update_cache_retries, update_cache_retry_max_delay, install_recommends (install-recommends), force_apt_get, dpkg_options, autoclean, only_upgrade, allow_unauthenticated (allow-unauthenticated), cache_valid_time, policy_rc_d, autoremove, upgrade, force, purge, state, fail_on_autoremove, deb, package (name, pkg), default_release (default-release)."}
```

**Comment by carlosmmatos** [comment]
@mstyne Thanks for opening up an issue here. I'm not seeing this behavior and I'm not able to replicate it via local testing or during our nightly CI. You can see the latest run [here](https://github.com/CrowdStrike/ansible_collection_falcon/actions/runs/5921821746/job/16054904616#step:8:794) on Ubuntu 22.04.

**Comment by carlosmmatos** [comment]
Here are the docs for builtin since the apt (ansible.builtin.apt): https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-allow_downgrade

What version of ansible-core are you running?

**Comment by mstyne** [comment]
@carlosmmatos My apologies, I am indeed running an older version of ansible-core (2.11). 

Thank you for investigating the issue further, and I'm sorry for not doing a bit more research on my own!

**Comment by carlosmmatos** [comment]
No worries, all good! Ansible did some weird stuff with their versioning which probably makes this all confusing.

**Comment by carlosmmatos** [comment]
I'm actually going to open up an issue to update our docs since that was based on the old way of versioning, so thanks for bringing this to light!

**Comment by carlosmmatos** [comment]
Closing this issue for now, if you have any further issues feel free to create a new one.
