### ISSUE TITLE
Error installing crowdstrike via token.

### ISSUE THREAD

**Issue by rscott1010101** [CrowdStrike/ansible_collection_falcon#39]
using a very simple playbook:-
---
- hosts: testhost1
  roles:
  - role: crowdstrike.falcon.falcon_installation
  vars:
    falcon_api_client_id: my_oauth_token
    falcon_api_client_secret: my_oauth_id

It downloads and installs the client correctly, then fails with:-
fatal: [testhost1]: FAILED! => {"msg": "The conditional check 'falcon_cid' failed. The error was: Invalid conditional detected: invalid syntax (<unknown>, line 1)\n\nThe error appears to be in '/home/ubuntu/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_installation/tasks/install.yml': line 73, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: CrowdStrike Falcon | Associate Falcon Sensor with your Customer ID (CID)\n    ^ here\n"}

If I set the falcon_cid variable, then it fails with a different error, 
TASK [falcon_installation : CrowdStrike Falcon | Associate Falcon Sensor with your Customer ID (CID)] ***************************************************************************************
task path: /home/ubuntu/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_installation/tasks/install.yml:73
[DEPRECATION WARNING]: evaluating 'falcon_cid' as a bare variable, this behaviour will go away and you might need to add |bool to the expression in the future. Also see CONDITIONAL_BARE_VAR
configuration toggle. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [infduoproxy1.tcore.com]: FAILED! => {"msg": "The conditional check 'falcon_cid' failed. The error was: template error while templating string: expected token 'end of statement block'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'. String: {% if xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-xx %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/ubuntu/.ansible/collections/ansllections/crowdstrike/falcon/roles/falcon_installation/tasks/install.yml': line 73, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line  to be:\n\n\n  - name: CrowdStrike Falcon | Associate Falcon Sensor with your Customer ID (CID)\n    ^ here\n"}

(replaced by cid with xxx). 

Could the error be because my CID has a - in it?

**Comment by jkramer-mythic** [comment]
I ran into this as well - I was able to resolve it by editing install.yml and changing this task from:

`
  - name: CrowdStrike Falcon | Associated Falcon Sensor with your Customer ID (CID) Using Provisioning Token
    command: "/opt/CrowdStrike/falconctl -s -f --cid={{ falcon_cid }} --provisioning-token={{ falcon_provisioning_token }}"
    when:
      - falcon_provisioning_token
      - falcon_cid
      - ansible_facts.packages
      - installed_sensor in ansible_facts.packages
      - ansible_distribution != "MacOSX"
`
to
`
  - name: CrowdStrike Falcon | Associated Falcon Sensor with your Customer ID (CID) Using Provisioning Token
    command: "/opt/CrowdStrike/falconctl -s -f --cid={{ falcon_cid }} --provisioning-token={{ falcon_provisioning_token }}"
    when:
      - falcon_provisioning_token
      - falcon_cid is defined
      - ansible_facts.packages
      - installed_sensor in ansible_facts.packages
      - ansible_distribution != "MacOSX"
`

**Comment by redhatrises** [comment]
Hello,

Thanks for reporting this! The role should grab the CID from the API. What version of ansible are you using? Ansible 2.10 is what is supported.

**Comment by rscott1010101** [comment]
I was using Ansible 2.9.6 (default install with Ubuntu 20.04) - upgraded to 2.10 and the playbook runs. Thanks!

Might be good to mention the requirement somewhere though?

**Comment by redhatrises** [comment]
> I was using Ansible 2.9.6 (default install with Ubuntu 20.04) - upgraded to 2.10 and the playbook runs. Thanks!
> 
> Might be good to mention the requirement somewhere though?

Requirements are currently in the Ansible role's readme, but I this shows that they do need to be clearer.

**Comment by redhatrises** [comment]
Closing the Ansible version that is required is mentioned in the role README which is now link accessible through the main README.
