### ISSUE TITLE
Required changes for Red Hat certification

### ISSUE THREAD

**Issue by evanstoner** [CrowdStrike/ansible_collection_falcon#432]
Per partner newsletter:

- [x] Upcoming Ansible Lint version bump - Certification will require v6.22.x in Q1 2024.
- [ ] Version 2.13 of Ansible Core reached EoL on November 26, 2023. Update your Certified Collection’s `meta/runtime.yml` file with a “requires_ansible” value of at least “>=2.14.0”.

**Comment by carlosmmatos** [comment]
Closed by
#434 
#433
