### ISSUE TITLE
Having issues installing crowdstrike with galaxy

### ISSUE THREAD

**Issue by vikas-falconx** [CrowdStrike/ansible_collection_falcon#435]
OS: Ubuntu 22
Ansible version: 8.2.0

I have been using it successfully so far but last few days i am having issues with installing Crowdstrike with galaxy here is the snippet of issue i am facing 

```

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Build API Sensor Query (Linux)] ****************************************
task path: /usr/share/ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/api.yml:89
ok: [localhost] => {
    "ansible_facts": {
        "falcon_os_query": "os:\"Ubuntu\"+os_version:\"*22*\"+os_version:!~\"arm64\"+os_version:!~\"zLinux\"+version:\"7.02.15705\""
    },
    "changed": false
}

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Build API Sensor Query (MacOS)] ****************************************
task path: /usr/share/ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/api.yml:95
skipping: [localhost] => {
    "changed": false,
    "false_condition": "ansible_facts['system'] == \"Darwin\"",
    "skip_reason": "Conditional result was False"
}

TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Get list of filtered Falcon sensors] ***********************************
task path: /usr/share/ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_install/tasks/api.yml:101
fatal: [localhost]: FAILED! => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"
}
```

**Comment by carlosmmatos** [comment]
Hi @vikas-falconx 

1. What version of our collection are you using? 

1. When you say "with galaxy", I'm not sure what that means. What other ways are you using to install/use the crowdstrike.falcon collection? Generally you use `ansible-galaxy collection instal...` to install a collection. I just want to make sure I understand your environment a little better.

1. If you set the `falcon_api_enable_no_log` var to `false` you will be able to see the output in the last task where it errored out. Try running it again so we can get a better idea of what that task is doing. Make sure to set verbosity to at least 3 (-vvv).

**Comment by vikas-falconx** [comment]
1.) Collection version  we areusig is 3.3.1
2.) I am using the same ansible-galaxy install only 
3.) This is what i get when i enable the logs 
```
fatal: [localhost]: FAILED! => {
    "msg": "Unexpected templating type error occurred on (https://{{ falcon_cloud }}/sensors/combined/installers/v1?sort=version|desc&filter={{ falcon_os_query | urlencode }}): unsupported format string passed to AnsibleUnsafeBytes.__format__. unsupported format string passed to AnsibleUnsafeBytes.__format__"
}
```

**Comment by carlosmmatos** [comment]
Let me test it that really quick to make sure nothing changed for v3 on the Ansible side.

**Comment by carlosmmatos** [comment]
Closing this since it has since been fixed: https://github.com/ansible/ansible/issues/82375
