### ISSUE TITLE
"filter": "os:'SLES_SAP'+os_version:'*12*'+os_version:!~'arm64'+os_version:!~'zLinux'","msg": "No Falcon Sensor was found! If passing in falcon_sensor_version, ensure it is correct!",

### ISSUE THREAD

**Issue by kenadyinampudi** [CrowdStrike/ansible_collection_falcon#453]
"filter": "os:'SLES_SAP'+os_version:'*12*'+os_version:!~'arm64'+os_version:!~'zLinux'",
"msg": "No Falcon Sensor was found! If passing in falcon_sensor_version, ensure it is correct!",

the latest version 4.2.2 was supposed to fix this issue.
![image](https://github.com/CrowdStrike/ansible_collection_falcon/assets/80376300/10000568-6213-411f-b37c-db951f76ff1d)
I am using the latest release and I still see this issue.
![image](https://github.com/CrowdStrike/ansible_collection_falcon/assets/80376300/dbae0c88-8df0-4c8d-848e-2bc8ac38bc1f)

![image](https://github.com/CrowdStrike/ansible_collection_falcon/assets/80376300/deabf000-0b5a-42be-8538-5bc662b3ea69)

and I have one more issue :
![image](https://github.com/CrowdStrike/ansible_collection_falcon/assets/80376300/a766ecd5-076b-4bd4-896a-a7785ca78c95)
zypper module is part of the community.general and comes with ansible core my execution environment has this but for some reason, it says module not found.

**Comment by carlosmmatos** [comment]
Will look into this soon. Thanks for opening up an issue!

**Comment by carlosmmatos** [comment]
Can you provide some info to help troubleshoot this:

- Output of:
```bash
ansible-galaxy collection list | grep falcon
```

- Output or screenshot of your facts for the target OS (ie, looking for ansible_distribution and ansible_os_family...)

Let's start there. Also, if you can share your playbook that is running this, that would be helpful too.

**Comment by carlosmmatos** [comment]
@kenadyinampudi Just checking in to see if you are still having this issue. If not, I'll close it out tomorrow since it's been 2 weeks without a response back.
