### ISSUE TITLE
ERROR: /opt/CrowdStrike/falconctl: unrecognized option '--message-log=True'

### ISSUE THREAD

**Issue by bufanda** [CrowdStrike/ansible_collection_falcon#476]
When using version 4.2.2 of the collection and trying to install an configure falcon 7.11.0-16405 on RHEL9
the ansible run stops with the error message

```
ERROR: /opt/CrowdStrike/falconctl: unrecognized option '--message-log=True'
```

also setting `falcon_message_log: "{{ None }}"`  explicity for RHEL9 systems doesn't work. We running also some RHEL8 Systems but with falcon 6.34 instead of 7.11 and running the same playbook works on the RHEL 8 combination.

**Comment by carlosmmatos** [comment]
@bufanda - `--message-log` was removed from the sensor starting on version 7.11. We have to keep it around due to supporting older versions. There will also be some additional parameters that will be added that have since been added with 7.11+.

I would do something like this:
```yaml
falcon_message_log: "{{ 'true' if (< RHEL 8 or some condition you define >) else None }}"
```

Another option would be to use group vars. Define a group for your 7.11+ hosts and a group for < 7.11 (however you want to to do this). Then you only need to define `falcon_message_log: 'true'` for the <7.11 group.

**Comment by bufanda** [comment]
I have tried to set `falcon_message_log: "{{ None}}"` but it just failed with 

```
ERROR: /opt/CrowdStrike/falconctl: unrecognized option '--message-log='
```

just missing the `True`. After setting `falcon_message_log:` without anything it worked and the task fell on the omit of the option to not add it.

**Comment by carlosmmatos** [comment]
Right.. this is not how you set none:
`falcon_message_log: "{{ None}}"`

The role already defines the [variable](https://github.com/CrowdStrike/ansible_collection_falcon/blob/main/roles/falcon_configure/defaults/main.yml#L92) as empty which will translate as None. So your second method is correct, outside of the fact that it's already defined so you really don't even have to provide it if you are not going to use the option.

**Comment by carlosmmatos** [comment]
`message_log: "{{ falcon_message_log if (falcon_message_log != None) else omit }}"`

As I'm remembering now - there was some oddity in the way Ansible was handling None or empty vars. The above conditional was accounting for either you weren't specifying an option, or you were. I don't think we tested trying to set it explicitly to None the way you have it.

**Comment by carlosmmatos** [comment]
No worries - unfortunately there is no real clean way to handle this on our side and eventually it would become irrelevant once < 7.11 is no longer supported. Appreciate you opening up the issue. I'm going to leave it open for a while since I have a feeling more users will run into the same issue.
