### ISSUE TITLE
Consider adding /docs to the collection

### ISSUE THREAD

**Issue by samccann** [CrowdStrike/ansible_collection_falcon#508]
This collection has two .md documentation files in the /docs dir, but that's not being included in the collection [here](https://github.com/CrowdStrike/ansible_collection_falcon/blob/main/galaxy.yml#L77), so users can't see this information on Automation Hub.  Consider adding it, so users can read those docs directly in the collection on Automation Hub.

**Comment by carlosmmatos** [comment]
Thanks @samccann ! Will get this fixed for 4.4.0 release.
