### ISSUE TITLE
Failed to validate GPG signature for falcon-sensor-7.17

### ISSUE THREAD

**Issue by TyraelTLK** [CrowdStrike/ansible_collection_falcon#536]
Hi,
with collection version 4.5.0 I'm getting:
`Failed to validate GPG signature for falcon-sensor-7.17.0-17005.el9.x86_64: Public key for falcon-sensor-7.17.0-17005.el9.x86_64.rpm is `

I think it's beacause the CrowdStrike Falcon sensor for Linux version 7.17 RPMs released in June 2024 are signed by a new key.

https://supportportal.crowdstrike.com/s/article/Tech-Alert-Cryptography-Announcement-Falcon-Sensor-for-Linux-RPM-Signing-Key-Update-June-2024

**Comment by carlosmmatos** [comment]
@TyraelTLK Thanks for bringing this up. I will get this fixed for 4.5.1.
