### ISSUE TITLE
TASK [crowdstrike.falcon.falcon_install : CrowdStrike Falcon | Download Falcon Sensor Installation Package (local)]

### ISSUE THREAD

**Issue by vkeyur** [CrowdStrike/ansible_collection_falcon#545]
Subject task is downloading package to ansible control host for each remote host in inventory, which is stalling ansible run when run on large number of remote host.  Is it possible to add "run_once: true" in task https://github.com/CrowdStrike/ansible_collection_falcon/blob/bc14fd914026ba46822ae30f30e121ba154fe84f/roles/falcon_install/tasks/api.yml#L63 ?

Thank you

**Comment by carlosmmatos** [comment]
Hi @vkeyur - appreciate you opening an issue up. 

With the [crowdstrike.falcon.sensor_download](https://crowdstrike.github.io/ansible_collection_falcon/sensor_download_module.html) if no `dest` is given, it will generate a temporary directory for each host it runs against. To prevent this, you can set the following variable for the `falcon_install` role:
```yaml
falcon_api_sensor_download_path: /path/you/want/the/installers/to/go
``` 

So if you set this to:
```yaml
falcon_api_sensor_download_path: /tmp
```

This means that for each host it targets, it will download the sensor to the /tmp directory like such: `/tmp/falcon-sensor_6.78.9-12345.deb`. Once its downloaded, it shouldn't be re-downloaded as the hash will match for subsequent runs. 

Please let me know if this works/helps. If not, happy to troubleshoot and figure out a solution.

**Comment by vkeyur** [comment]
Thank you, that helped.
