### ISSUE TITLE
Run once when downloading the package

### ISSUE THREAD

**Issue by dpzx** [CrowdStrike/ansible_collection_falcon#547]
Please add run_once when downloading the installation package:

roles/falcon_install/tasks/api.yml

```python 
- name: CrowdStrike Falcon | Download Falcon Sensor Installation Package (local)
  crowdstrike.falcon.sensor_download:
    auth: "{{ falcon.auth }}"
    hash: "{{ falcon_api_installer_list.installers[falcon_sensor_version_decrement | int].sha256 }}"
    dest: "{{ falcon_api_sensor_download_path | default(omit, true) }}"
    name: "{{ falcon_api_sensor_download_filename | default(omit, true) }}"
    mode: "{{ falcon_api_sensor_download_mode | default(omit, true) }}"
    owner: "{{ falcon_api_sensor_download_owner | default(omit, true) }}"
    group: "{{ falcon_api_sensor_download_group | default(omit, true) }}"
  changed_when: false
  register: falcon_sensor_download
  delegate_to: localhost
  run_once: yes
```

**Comment by carlosmmatos** [comment]
Please refer to #545 

I'll add a note to update the docs for this as this has popped up more than once.

**Comment by redhatrises** [comment]
> Also we use k8s agents and it will always download the package since the pod/containers are created on demand.

If you are installing the sensor rpm/deb package into pods/containers via ansible, this is unsupported by the sensor itself. You will need to use the helm chart or operator and install the daemonset or sidecar to properly handle k8s pods and containers.

**Comment by dpzx** [comment]
localhost is the ansible controller, we are using the agent to install it on vms

**Comment by carlosmmatos** [comment]
> This should still be added, why are we downloading the same package to same path on localhost? This should only be done once and then transferred to the remote hosts. Also we use k8s agents and it will always download the package since the pod/containers are created on demand.

The reason we aren't using `run_once` is because most users don't have a homogeneous environment, so this way we can ensure that the appropriate sensors are downloaded for their respective OS's.

**Comment by dpzx** [comment]
Can you give me an example of how you would use this role that's not homogeneous?

**Comment by carlosmmatos** [comment]
As I mentioned, in your scenario, if you use `run_once` against windows and linux hosts in the same run - then I'm sure you know what will happen.. At this moment we're not planning on making too many changes to the existing roles (unless its a bug). They are there as a nice to have for folks that don't feel like building out their own. But with that being said, feel free to either:
- fork this and chop it up how you deem necessary
- use our existing modules to query/download the sensors and build out your own playbooks/roles that work for you

Hopefully setting the `falcon_api_sensor_download_path` is all you need to continue using this, but I understand if you want to take a different approach.

I'll close this as there is not any changes to be made. Appreciate you discussing with us.
