### ISSUE TITLE
api.

### ISSUE THREAD

**Issue by brunoneron** [CrowdStrike/ansible_collection_falcon#55]
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'unicode object' has no attribute 'sha256'\n\nThe error appears to be in '/root/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_installation/tasks/api.yml': line 48, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: CrowdStrike Falcon | Download Latest Sensor Installation Package\n  ^ here\n"}

*** Please add " | list " into api.yaml line 36
Current
falcon_api_sha_hash: "{{ falcon_api_installer_list.json.resources | selectattr('os_version', 'equalto', ansible_distribution_major_version ) }}"

Modified
falcon_api_sha_hash: "{{ falcon_api_installer_list.json.resources | selectattr('os_version', 'equalto', ansible_distribution_major_version ) | list }}"

**Comment by redhatrises** [comment]
This should be fixed now. `falcon_api_sha_hash` no longer is used.

**Comment by redhatrises** [comment]
See #68
