### ISSUE TITLE
latest version now fails on UBUNTU due to equals_to

### ISSUE THREAD

**Issue by gamethis** [CrowdStrike/ansible_collection_falcon#56]
The change to equals_to in this commit causes ubuntu builds to fail due to 
os_version formating in the api being more than one version.
`os_version: 16/18/20`

this pr introduced here in #53 at line 36 of api.yml

see diff here.

https://github.com/CrowdStrike/ansible_collection_falcon/pull/53/files#diff-92a8f4eb3b1dc2dd3ec492d56697e6c4e075a33e3cc4a7d3eebfbf2802da3dbfR36

**Comment by redhatrises** [comment]
Should be fixed with #57  PR merged.
