### ISSUE TITLE
Regression: falcon_configure no longer re-sets the provisioning token when falcon_remove_aid is set

### ISSUE THREAD

**Issue by nhinds** [CrowdStrike/ansible_collection_falcon#579]
The change in #565 pipes both `options.cid` and `options.provisioning_token` through the `| bool` filter. The `bool` filter treats  `"yes"`, `"on"`, `"1"`, and `"true"` as `true`, and all other values as `false`.

The values for CID and provisioning token will be treated as `false` by `| bool`, and so the "Master Image Prep | Set Provisioning Token (if applicable)" task is skipped. This means that the fix from #546 to set provisioning token after removing the AID is not working any longer.
```
TASK [crowdstrike.falcon.falcon_configure : CrowdStrike Falcon | Master Image Prep | Removing AID] ***
changed: [localhost]

TASK [crowdstrike.falcon.falcon_configure : CrowdStrike Falcon | Master Image Prep | Set Provisioning Token (if applicable)] ***
skipping: [localhost]
```

It seems like the tests for this scenario are not asserting that the provisioning token is set, as e.g. the latest test run https://github.com/CrowdStrike/ansible_collection_falcon/actions/runs/12061458954/job/33633526983 also skipped this task:
```
  TASK [crowdstrike.falcon.falcon_configure : CrowdStrike Falcon | Wait for Falcon Sensor to Generate AID] ***
  Thursday 28 November 2024  02:39:33 +0000 (0:00:01.766)       0:00:06.428 *****
  FAILED - RETRYING: [ubuntu-22.04-falcon_configure_remove_aid]: CrowdStrike Falcon | Wait for Falcon Sensor to Generate AID (6 retries left).
  FAILED - RETRYING: [ubuntu-22.04-falcon_configure_remove_aid]: CrowdStrike Falcon | Wait for Falcon Sensor to Generate AID (5 retries left).
  ok: [ubuntu-22.04-falcon_configure_remove_aid] => {"attempts": 3, "changed": false, "falconctl_info": {"aid": "e84bdabbf45e4d04b73fa9a61bcd3bbe"}}
  
  TASK [crowdstrike.falcon.falcon_configure : CrowdStrike Falcon | Master Image Prep | Removing AID] ***
  Thursday 28 November 2024  02:39:55 +0000 (0:00:22.522)       0:00:28.950 *****
  changed: [ubuntu-22.04-falcon_configure_remove_aid] => {"changed": true}
  
  TASK [crowdstrike.falcon.falcon_configure : CrowdStrike Falcon | Master Image Prep | Set Provisioning Token (if applicable)] ***
  Thursday 28 November 2024  02:39:56 +0000 (0:00:00.803)       0:00:29.753 *****
  skipping: [ubuntu-22.04-falcon_configure_remove_aid] => {"changed": false, "false_condition": "options.cid | bool", "skip_reason": "Conditional result was False"}
```

**Comment by carlosmmatos** [comment]
@nhinds - another good find! Appreciate you opening these up and providing context, especially pointing to the CI runs! I'm over here shaking my head wondering how the heck I missed this when I was doing the other PR's that were supposed to fix it 🤦🏼‍♂️ ... 

We'll get something out for this next week 👊🏼

**Comment by nhinds** [comment]
I've also found that if `falcon-sensor.service` is running at the point when the provisioning token is set, sometimes it re-activates itself a few minutes later. This consumes the provisioning token and makes our AMI build fail, as we have a step that verifies there is no agent ID set before stopping the EC2 instance.

It seems like stopping `falcon-sensor.service` before setting the provisioning token avoids this. We used to do this in an older version of the Ansible collection, but as mentioned in https://github.com/CrowdStrike/ansible_collection_falcon/issues/534#issuecomment-2259439706 it is no longer possible to pass `falcon_service_state: stopped` due to the "Wait for Falcon Sensor to Generate AID" task which requires the service to be running.

I can split this out to a different issue if you would prefer to tackle it separately, but this behavior means that even if the "Master Image Prep | Set Provisioning Token" step was to run it would not work correctly for us.

**Comment by nhinds** [comment]
> What do you mean by "sometimes"? It shouldn't unless something restarts the service, otherwise I think this is a bug in the sensor itself. If this is something you can confirm I would highly suggest opening a bug with support.

Sometimes the aid is absent as expected, sometimes it is present. On one of the times that it failed I inspected the build instance and confirmed the service had not been restarted in systemd, but falcon had re-activated itself about a minute after the initial activate+clean. I haven't noticed a pattern around when this happens, I suspect it may be to do with how quickly the other image prep steps complete. I'll reproduce and capture the full logs to pass onto support.

**Comment by nhinds** [comment]
The support case is still open, but for what it's worth it seems like `falcon-sensor` will restart itself to apply an upgrade or downgrade if the sensor update policy in the Falcon console thinks it should be running a different version. Enabling trace shows the message "info: Restarting to apply cloud update" in the falcon sensor logs just before it restarts / re-activates and consumes the provisioning token.

For me this was caused by asking Ansible to use the version from the `platform_default` policy, but then a different sensor update policy ended up being applied when the sensor activated. I've got a workaround for this specific case: align my update policies.

It still sort of feels like the service should be stopped prior to image preparation in case the version from the sensor update policy changes while the build is in progress (e.g. if a new sensor version is rolled out after the Ansible has run but before the AMI is created, or if an admin is editing the policies), but if the initial version matches then it should at least be less likely to cause problems.

**Comment by carlosmmatos** [comment]
I see. This should be doable and shouldn’t affect anything else. I’ll work on the PR tomorrow.

**Comment by nhinds** [comment]
Thanks, I can confirm the changes now let me set the provisioning token and stop the service in my AMI build

**Comment by carlosmmatos** [comment]
@nhinds  I’ll get a new release out here soon
