### ISSUE TITLE
getting error when installing using on windows

### ISSUE THREAD

**Issue by warrenridley** [CrowdStrike/ansible_collection_falcon#86]
"fatal: [*.*.*.*]: FAILED! => {"changed": false, "character_set": null, "content": "", "content_encoding": "", "content_length": "0", "content_type": "", "cookies": [], "date": "Thu, 09 Dec 2021 15:52:02 GMT", "elapsed": 0, "headers": ["Strict-Transport-Security", "X-Cs-Region", "X-Cs-Traceid", "X-Ratelimit-Limit", "X-Ratelimit-Remaining", "Content-Length", "Date", "Location"], "is_from_cache": false, "is_mutually_authenticated": false, "last_modified": "2021-12-09T15:52:02.9575943+00:00", "location": "https://api.us-2.crowdstrike.com/oauth2/token", "method": "POST", "msg": "Status code of request '308' is not in list of valid status codes 201 : 308'.", "protocol_version": {"Build": -1, "Major": 1, "MajorRevision": -1, "Minor": 1, "MinorRevision": -1, "Revision": -1}, "response_uri": "https://api.crowdstrike.com/oauth2/token", "server": "", "status_code": 308, "status_description": "Permanent Redirect", "strict_transport_security": "max-age=31536000; includeSubDomains", "supports_headers": true, "url": "https://api.crowdstrike.com/oauth2/token", "x_cs_region": "us-2", "x_cs_traceid": "******************", "x_ratelimit_limit": "300", "x_ratelimit_remaining": "299""

**Comment by redhatrises** [comment]
@warrenridley is your API configured with non-expired tokens with the correct API permissions for your region? Also, are you manually specifying us-2?

**Comment by warrenridley** [comment]
yes it is configured with the correct API permissions.  I ran this

- hosts: all
    roles:
    - role: crowdstrike.falcon.falcon_installation
    vars:
      falcon_client_id: "**************************"
      falcon_client_secret: "**********************************"

**Comment by redhatrises** [comment]
Are you intentionally going through `us-2`?

If you can rerun again with adding `-vvv` and provide the output, that would be great.

**Comment by warrenridley** [comment]
ok got what you saying added 
falcon_cloud: "api.us-2.crowdstrike.com"

that solved the problem.

thank you.

**Comment by redhatrises** [comment]
Cool. Autodiscover isn't enabled yet. Opening a separate issue for that.
