### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by ktinthecloud** [CrowdStrike/ansible_collection_falcon#99]
Linux installations work fine, but getting the following error during Windows installations:

TASK [crowdstrike.falcon.falcon_installation : CrowdStrike Falcon | Download Falcon Sensor Installation Package] ***********************************************************************************************************
fatal: [hostname.MYDOMAIN.COM]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: list object has no element 0\n\nThe error appears to be in '/root/.ansible/collections/ansible_collections/crowdstrike/falcon/roles/falcon_installation/tasks/win_api.yml': line 73, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: CrowdStrike Falcon | Download Falcon Sensor Installation Package\n ^ here\n"}

I'm running Ansible version 2.12.1.

**Comment by redhatrises** [comment]
Hello,

This issue has already been fixed. Please see #90

**Comment by ktinthecloud** [comment]
That worked.  Thanks!  If I'm using the latest release (3.0.0), how come that fix is not included?  Do we just have to wait for CrowdStrike to merge these changes into a new release?  Sorry for the dumb questions, I'm new to github.

**Comment by redhatrises** [comment]
It was not delivered as part of the `3.0.0` release. The changes needed for the `3.1.0` release are being made right now.

**Comment by ktinthecloud** [comment]
Got it.  Thanks for the help @redhatrises
